### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by ZeldaZach** [taw/magic-preconstructed-decks#5]
Been fiddling around with this, but can't seem to figure out what's up.

ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

```bash
$ brew install bundle
$ bundle install --path vendor/bundle
$ bundle install
$ bundle exec bin/build_jsons decks.json
bundler: failed to load command: bin/build_jsons (bin/build_jsons)
NoMethodError: undefined method `compact' for {:name=>"Aquastrand Spider", :count=>1, :foil=>nil}:Hash
  /Users/zachary/Desktop/magic-preconstructed-decks/lib/deck.rb:37:in `block in card_data'
  /Users/zachary/Desktop/magic-preconstructed-decks/lib/deck.rb:32:in `map'
  /Users/zachary/Desktop/magic-preconstructed-decks/lib/deck.rb:32:in `card_data'
  bin/build_jsons:24:in `add_deck'
  bin/build_jsons:51:in `validate_and_add_deck'
  bin/build_jsons:142:in `block in build'
  bin/build_jsons:140:in `each'
  bin/build_jsons:140:in `build'
  bin/build_jsons:154:in `<top (required)>'
```

**Comment by taw** [comment]
You get error about `compact` in ruby 2.5?

Probably something wrong with your installation, but I added `hash-polyfill` gem to this so it can run on ruby 2.3.

**Comment by ZeldaZach** [comment]
Appreciated
